# Generated by Django 2.1.5 on 2019-02-02 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('google', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestSites',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=128)),
            ],
        ),
        migrations.RemoveField(
            model_name='loadtimes',
            name='url',
        ),
        migrations.AddField(
            model_name='loadtimes',
            name='url_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='google.TestSites'),
            preserve_default=False,
        ),
    ]
